<?php
include_once('Model/Crud/Adm.php');
include_once('Model/Crud/Membro.php');
include_once('Model/Crud/Artigo.php');
include_once('Model/Crud/Livro.php');
include_once('Model/Crud/Tcc.php');
include_once('Model/Crud/Tese.php');
include_once('Model/Crud/Dissertacao.php');
include_once('Model/Crud/Imagem.php');
include_once('Model/Crud/Noticia.php');
include_once('Model/Crud/Galeria.php');
?>