<?php
include_once('Model/Crud/Adm.php');
include_once('Model/Crud/Membro.php');
include_once('Model/Crud/Artigo.php');
include_once('Model/Crud/Livro.php');
include_once('Model/Crud/Tcc.php');
include_once('Model/Crud/Tese.php');
include_once('Model/Crud/Dissertacao.php');
?>